-- Game
INSERT INTO game (game_name, estimated_completion_time, game_overview, esrb_rating, difficulty, average_rating, release_date, price) VALUES ('Gotham_Knights',020.00,'Gotham Knights is a brand-new open world, third-person action RPG featuring the Batman Family as players step into the roles of Batgirl, Nightwing, Red Hood, and Robin, a new guard of trained DC Super Heroes who must rise up as the protectors of Gotham City in the wake of Batman''s death. An expansive, criminal underworld has swept through the streets of Gotham, and it is now up to these new heroes to protect the city, bring hope to its citizens, discipline to its cops and fear to its criminals. Players must save Gotham from descent into chaos and reinvent themselves into their own version of the Dark Knight. - GameStop & Walmart', 'TEEN', 'NORMAL', 06.4, '2022-10-21', 069.99);
INSERT INTO game (game_name, estimated_completion_time, game_overview, esrb_rating, difficulty, average_rating, release_date, price) VALUES ('FIFA_23', 075.00, 'EA SPORTS™ FIFA 23 brings even more of the action and realism of football to the pitch in The World''s Game, with advances in HyperMotion2 Technology driven by twice as much real-world motion capture helping to create more true football animation than ever before in every match. Play the biggest tournaments in football with both the men''s and women''s FIFA World Cup™ coming to FIFA 23 during the season, play as women''s club teams – powered by dedicated HyperMotion2 animation – for the first time ever, plus enjoy cross-play features that make it easier to play against friends. Enjoy a new way to play and build your dream squad in FIFA Ultimate Team™ with FUT Moments and a revamped Chemistry system, or live out your football dreams in Career Mode as you define your personality as a player and manage as some of football''s most famous names. In VOLTA FOOTBALL and Pro Clubs, bring more personality to the pitch with new levels of customization and enhanced street and stadium gameplay. However you play, experience The World''s Game with over 19,000 players, 700+ teams, 100+ stadiums, and over 30 leagues - including the UEFA Champions League, Premier League, new Barclays FA Women''s Super League and France D1 Arkema with unrivaled authenticity in FIFA 23. – GameStop & Walmart', 'EVERYONE', 'EASY', 07.6, '2022-09-27', 069.99);
INSERT INTO game (game_name, estimated_completion_time, game_overview, esrb_rating, difficulty, average_rating, release_date, price) VALUES ('Pokemon_Legends:Arceus', 042.50, 'Get ready for a new kind of grand, Pokémon adventure in Pokémon™ Legends: Arceus, a brand-new game from Game Freak that blends action and exploration with the RPG roots of the Pokémon series. Embark on survey missions in the ancient Hisui region. Explore natural expanses to catch wild Pokémon by learning their behavior, sneaking up, and throwing a well-aimed Poké BallTM. You can also toss the Poké Ball containing your ally Pokémon near a wild Pokémon to seamlessly enter battle. - GameStop & Walmart', 'EVERYONE', 'NORMAL', 04.7, '2022-01-28', 049.99);
INSERT INTO game (game_name, estimated_completion_time, game_overview, esrb_rating, difficulty, average_rating, release_date, price) VALUES ('Marvels_Spider-Man:Miles_Morales', 012.00, 'Take on the mean streets of Manhattan as a new Spider-Man. Marvel''s Spider-Man: Miles Morales introduces you to the rise of a new hero. In the latest adventure in the Spider-verse, teenager Miles Morales is adjusting to his new home while following in the footsteps of his mentor, Peter Parker. But when a fierce power struggle threatens to destroy his new home, the aspiring hero realizes that with great power, there must also come great responsibility. To save all of Marvel''s New York, Miles must take up the mantle of Spider-Man and own it. - GameStop', 'TEEN', 'NORMAL', 09.2, '2021-11-12', 024.99);
INSERT INTO game (game_name, estimated_completion_time, game_overview, esrb_rating, difficulty, average_rating, release_date, price) VALUES ('Elden_Ring', 098.50, 'The Golden Order has been broken. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.A NEW FANTASY WORLD Journey through the Lands Between, a new fantasy world created by Hidetaka Miyazaki, creator of the influential DARK SOULS video game series, and George R. R. Martin, author of The New York Times best-selling fantasy series, A Song of Ice and Fire. Unravel the mysteries of the Elden Ring''s power. GENRE-DEFINING GAMEPLAY Create your character in FromSoftware''s refined action-RPG and define your play style by experimenting with a wide variety of weapons, magical abilities, and skills found throughout the world. Charge into battle, pick off enemies one-by-one using stealth, or even call upon allies for aid. - Walmart', 'MATURE_17PLUS', 'EXPERT', 09.2, '2022-02-25', 059.99);

-- Genre
INSERT INTO genre (genre_name) VALUES ('Action');
INSERT INTO genre (genre_name) VALUES ('Sports');
INSERT INTO genre (genre_name) VALUES ('Board/Card Game');
INSERT INTO genre (genre_name) VALUES ('Fighting');
INSERT INTO genre (genre_name) VALUES ('Puzzle');
INSERT INTO genre (genre_name) VALUES ('Racing');
INSERT INTO genre (genre_name) VALUES ('Role-Playing Game');
INSERT INTO genre (genre_name) VALUES ('Shooter');
INSERT INTO genre (genre_name) VALUES ('Simulation');
INSERT INTO genre (genre_name) VALUES ('Adventure');

-- Review
INSERT INTO review (game_id, reviewer_name, reviewer_timestamp, review_rating, review_text) VALUES (3, 'Mister Chief', '2022-08-26', 'FIVE_STARS', 'A fresh breath of air from a long standing franchise');
INSERT INTO review (game_id, reviewer_name, reviewer_timestamp, review_rating, review_text) VALUES (3, 'Jannie0130', '2022-08-23', 'FIVE_STARS', 'It''s super fun to play even if you''re not a super Pokemon fan or if you don''t know much about Pokemon');
INSERT INTO review (game_id, reviewer_name, reviewer_timestamp, review_rating, review_text) VALUES (4, 'JRome21', '2022-09-16', 'FOUR_STARS', 'Fun game and a good story all the way through. A game that is at the same level as the previous.');
INSERT INTO review (game_id, reviewer_name, reviewer_timestamp, review_rating, review_text) VALUES (5, 'Brian34', '2022-07-14', 'FIVE_STARS', 'Really good game. Love that they went to this wide open world. Great addition to the Dark Souls Series');
INSERT INTO review (game_id, reviewer_name, reviewer_timestamp, review_rating, review_text) VALUES (1, 'James', '2022-10-21', 'FIVE_STARS', 'If you enjoy superhero games then do yourself a favor and pick this up!!');
INSERT INTO review (game_id, reviewer_name, reviewer_timestamp, review_rating, review_text) VALUES (1, 'Peter Driscoll', '2022-10-22', 'ONE_STAR', 'I made it through 4 hours. The frames aren''t the issue, it''s so repeditive and the characters are lifeless. It visually looks like a PS4 launch game. WTF. If my name was Karen, I would demand to speak to a manager.');

-- Game Genre
INSERT INTO game_genre (game_id, genre_id) VALUES (1, 1);
INSERT INTO game_genre (game_id, genre_id) VALUES (2, 2);
INSERT INTO game_genre (game_id, genre_id) VALUES (3, 10);
INSERT INTO game_genre (game_id, genre_id) VALUES (4, 1);
INSERT INTO game_genre (game_id, genre_id) VALUES (5, 1);
